name: nepek_buyer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^5.0.0
  google_fonts: ^2.0.0
  http: ^0.13.0
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.0.0
  smooth_star_rating: ^1.1.1
  flutter_swiper: ^1.1.6
  intl: ^0.17.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  image_picker: ^0.7.4
  # hive_flutter: ^0.3.1
  path_provider: ^2.0.1
  firebase_core: ^1.2.0
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  percent_indicator: ^3.0.1    
  flutter_rating_bar: ^4.0.0 
  flutter_page_indicator:   
  carousel_slider: ^3.0.0
  flutter_statusbarcolor: ^0.2.3
  transparent_image: ^2.0.0
  random_color: ^1.0.5
  photo_view: ^0.11.1
  share: ^2.0.1
  rive: ^0.7.5
  image_cropper: ^1.2.3
  firebase_messaging: ^10.0.0
  uuid: ^3.0.4
  flutter_native_image: ^0.0.5
  webview_flutter: ^2.0.4
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^6.0.3
  firebase_performance: ^0.7.0+3
  firebase_crashlytics: ^2.0.4
  firebase_analytics: ^8.1.0
  page_transition: ^2.0.2

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7+1
  


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/nepek_main.png"
  image_path_android: "assets/launcher/nepek_main.png"
  adaptive_icon_background: "assets/launcher/nepek_background.png"
  adaptive_icon_foreground: "assets/launcher/nepek_foreground.png" 
  remove_alpha_ios: true 

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bottomNavBar/
    - assets/others/
    - assets/profileTab/
    - assets/product/
    - animations/
    - assets/noProductsFound/
    - assets/homepage/top_part/



flutter_native_splash:
  color: "#ffffff"
  image: "assets/others/Brand.png"
  ios: true
  android: true
  

        